version: '3.8'

services:
  scheduler:
    build: .
    container_name: megaeth-scheduler
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_PATH=/app/config.yaml
    working_dir: /app
    command: python scheduler.py 