version: '3.8'

services:
  scheduler:
    build: .
    container_name: megaeth-scheduler
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: python scheduler.py 