version: '3.8'

services:
  faucet-bot:
    build: .
    volumes:
      - ./config.json:/app/config.json
    environment:
      - AUTO_MODE=true
    restart: unless-stopped

  task-bot:
    build: .
    volumes:
      - ./config.json:/app/config.json
    environment:
      - AUTO_MODE=true
      - BOT_TYPE=task
    restart: unless-stopped

  scheduler:
    build: .
    container_name: megaeth-scheduler
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_PATH=/app/config.yaml
    working_dir: /app
    command: python scheduler.py 